### ISSUE TITLE
understanding data preparation

### ISSUE THREAD

**Issue by christinazavou** [czq142857/DECOR-GAN#1]
Hello, 
thanks for publishing your code :)

I have the following questions regarding the 3 possible scripts for step 3:
 - is there some documentation on how depth fusion is done & what is the difference between depth fusion and flood fill approach? 
 - Is the dimension 2560 for rendering variable arbitrarily chosen? and why is state_ctr shape 512x512x64, 2?
 - what should be the difference between the initial .binvox created in step 2 and the .binvox created in step 3?

Thanks in advance

**Comment by czq142857** [comment]
![image](https://user-images.githubusercontent.com/24209790/119235716-c5e17c00-bae8-11eb-93e4-43a2eb469cba.png)

Sorry, but there is no such documentation... I just wrote the code based on the above figure.

Basically, depth fusion marks the visible voxels (before the shape surface) with 0s and invisible voxels (behind the shape surface) with 1s. In *3_depthfusion_17views.py*, I used 17 views as shown in the above figure, to decide whether a voxel is visible or not. In *3_depthfusion_5views.py*, I just used top/front/back/left/right five views. Note that usually depth fusion reconstructs the voxels/SDFs from depth images, but the input of my code is already a voxel grid (although it will be converted into depth maps in the process).

rendering = np.zeros([2560,2560,17], np.int32)
This is to store depth maps, considering that the input voxel grid is *512*.

state_ctr = np.zeros([512\*512\*64,2], np.int32)
This is to store the binvox format, i.e., a sequence of (state, number). Please check the format description of binvox for more details.

Both numbers are set to be large enough to avoid "list index out of range" error. I was too lazy to set the sizes dynamically.

On the other hand, floodfill uses a different approach and requires higher shape quality. Please check the definition of floodfill for more details.

The initial .binvox created in step 2 only contains surface voxels, i.e., inside-0, outside-0, on_surface-1. After step 3, we want to get occupancies, i.e., inside-1, outside-0, on_surface-1.

Best,
Zhiqin

**Comment by christinazavou** [comment]
Thanks for your explanation and figures!
