### ISSUE TITLE
the dilation in conv3d

### ISSUE THREAD

**Issue by hmax233** [czq142857/DECOR-GAN#4]
Thanks for your great work!
          After reading your paper, I have some questions about the dilation in conv3d and the patchDiscriminator, which puzzle me a lot.
         The discriminator and generator architecture figures in your paper show that you use conv3d with dilation=0 in some layers, for example, the layers in the discriminator. But in the script, the conv3d layers use default dilation, which is 1 according to [official explanation](https://pytorch.org/docs/stable/generated/torch.nn.Conv3d.html).
          So I want to know why is that. And I also can't find any articles to explain what conv3d with dilation=0 dose and how to utilize that to accomplish patchDiscriminator.

```
class discriminator(nn.Module):
    def __init__(self, d_dim, z_dim):
        super(discriminator, self).__init__()
        self.d_dim = d_dim
        self.z_dim = z_dim

        self.conv_1 = nn.Conv3d(1,             self.d_dim,    4, stride=1, padding=0, bias=True)
        self.conv_2 = nn.Conv3d(self.d_dim,    self.d_dim*2,  3, stride=2, padding=0, bias=True)
        self.conv_3 = nn.Conv3d(self.d_dim*2,  self.d_dim*4,  3, stride=1, padding=0, bias=True)
        self.conv_4 = nn.Conv3d(self.d_dim*4,  self.d_dim*8,  3, stride=1, padding=0, bias=True)
        self.conv_5 = nn.Conv3d(self.d_dim*8,  self.d_dim*16, 3, stride=1, padding=0, bias=True)
        self.conv_6 = nn.Conv3d(self.d_dim*16, self.z_dim,    1, stride=1, padding=0, bias=True)
```

**Comment by czq142857** [comment]
The figure in the supplementary material is wrong. Dilation cannot be 0. Please consider all dilation=0 as dilation=1.
